# Generated by Django 6.0.7 on 2026-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalFootprintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('positive', 'Positive Footprint'), ('negative', 'Negative Footprint'), ('passive', 'Passive Footprint'), ('active', 'Active Footprint')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fa-solid fa-fingerprint', max_length=50)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=200)),
            ],
        ),
    ]
