# Generated by Django 6.0.7 on 2026-08-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fa-solid fa-route', max_length=50)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
