# Generated by Django 6.0.7 on 2026-08-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_level',
            field=models.IntegerField(default=2, help_text='Current level in learning journey'),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0, help_text='Experience points earned'),
        ),
    ]
