# Generated by Django 6.0.7 on 2026-08-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_current_level_profile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0, help_text='In-game gold coins'),
        ),
        migrations.AddField(
            model_name='profile',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='knowledge_score',
            field=models.IntegerField(default=0, help_text='Score out of 100'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reputation_score',
            field=models.IntegerField(default=85, help_text='Score out of 100'),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_score',
            field=models.IntegerField(default=85, help_text='Score out of 100'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stars',
            field=models.IntegerField(default=0, help_text='Stars representing perfect level scores'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=85, help_text='Score out of 100'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_level',
            field=models.IntegerField(default=2, help_text='Current active level (1 to 20)'),
        ),
    ]
