# Generated by Django 6.0.7 on 2026-08-04 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon_emoji', models.CharField(default='🏆', max_length=10)),
                ('badge_code', models.CharField(max_length=50, unique=True)),
                ('criteria_type', models.CharField(help_text='e.g. FIRST_STEP, SAFE_STREAK, HIGH_SCORE, MASTER', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Sequence order of scenario (1, 2, 3...)', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='Category e.g. Social Media, Permanent Records, Privacy', max_length=100)),
                ('situation_text', models.TextField(help_text='Short real-life situation description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.IntegerField(default=0)),
                ('current_scenario_index', models.IntegerField(default=1, help_text='Current scenario order number user is on')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text shown to the user', max_length=255)),
                ('score_impact', models.IntegerField(help_text='Score change e.g. +10, +5, 0, -5, -10')),
                ('quality_type', models.CharField(choices=[('EXCELLENT', 'Excellent Choice'), ('GOOD', 'Good Choice'), ('NEUTRAL', 'Neutral Choice'), ('RISKY', 'Risky Choice'), ('DANGEROUS', 'Dangerous Choice')], default='GOOD', max_length=20)),
                ('explanation', models.TextField(help_text='Why this choice affects your digital footprint')),
                ('consequences', models.TextField(help_text='Long-term consequences of this choice')),
                ('tip', models.TextField(help_text='Actionable tip for safer digital footprint management')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='home.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_delta', models.IntegerField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.choice')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scenario__order'],
                'unique_together': {('user', 'scenario')},
            },
        ),
    ]
